import { useEffect } from 'react';
import './PrivacyPolicy.css';

const PrivacyPolicyPage = () => {
    useEffect(() => {
        window.scrollTo(0, 0);
    }, []);

    return (
        <div className="privacy-policy-page">
            <div className="privacy-policy-hero">
                <div className="container">
                    <h1>Privacy Policy</h1>
                </div>
            </div>

            <div className="privacy-policy-content container">
                <section>
                    <p>This privacy policy sets out how Diamantides Yachting uses and protects any information that you give to <a href="https://www.diamantidesyachting.com">www.diamantidesyachting.com</a> when you use this website.</p>
                    <p>Diamantides Yachting is committed to ensuring that your privacy is protected. Should we ask you to provide certain information by which you can be identified when using this website, then you can be assured that it will only be used in accordance with this privacy statement.</p>
                    <p>Diamantides Yachting may change this policy from time to time by updating this page. You should check this page from time to time to ensure that you are happy with any changes. This policy is effective from 01/12/2021.</p>
                </section>

                <section>
                    <h2>What we collect</h2>
                    <p>We may collect the following information:</p>
                    <ul>
                        <li>name</li>
                        <li>surname</li>
                        <li>contact number</li>
                        <li>email</li>
                    </ul>
                </section>

                <section>
                    <h2>What we do with the information we gather</h2>
                    <p>We require this information to understand your needs and provide you with a better service, and in particular for the following reasons:</p>
                    <ul>
                        <li>Internal record keeping.</li>
                        <li>We may use the information to improve our products and services.</li>
                        <li>We may periodically send promotional emails about new products, special offers or other information which we think you may find interesting using the email address which you have provided.</li>
                        <li>From time to time, we may also use your information to contact you for market research purposes. We may contact you by email, phone, fax or mail. We may use the information to customize the website according to your interests.</li>
                    </ul>
                </section>

                <section>
                    <h2>Security</h2>
                    <p>We are committed to ensuring that your information is secure. In order to prevent unauthorized access or disclosure, we have put in place suitable physical, electronic and managerial procedures to safeguard and secure the information we collect online.</p>
                </section>

                <section>
                    <h2>How we use cookies</h2>
                    <p>A cookie is a small file that asks permission to be placed on your computer’s hard drive. Once you agree, the file is added and the cookie helps analyse web traffic or lets you know when you visit a particular site. Cookies allow web applications to respond to you as an individual. The web application can tailor its operations to your needs, likes and dislikes by gathering and remembering information about your preferences.</p>
                    <p>We use traffic log cookies to identify which pages are being used. This helps us analyse data about web page traffic and improve our website in order to tailor it to customer needs. We only use this information for statistical analysis purposes and then the data is removed from the system.</p>
                    <p>Overall, cookies help us provide you with a better website, by enabling us to monitor which pages you find useful and which you do not. A cookie in no way gives us access to your computer or any information about you, other than the data you choose to share with us.</p>
                    <p>You can choose to accept or decline cookies. Most web browsers automatically accept cookies, but you can usually modify your browser setting to decline cookies if you prefer. This may prevent you from taking full advantage of the website.</p>
                </section>

                <section>
                    <h2>Google Analytics</h2>
                    <p>This website uses Google Analytics, a web analytics service provided by Google, Inc. (“Google”). Google Analytics uses “cookies”, which are text files placed on your computer, to help the website analyze how users use the site. The information generated by the cookie about your use of the website will be transmitted to and stored by Google on servers in the United States.</p>
                    <p>In case IP-anonymisation is activated on this website, your IP address will be truncated within the area of Member States of the European Union or other parties to the Agreement on the European Economic Area. Only in exceptional cases the whole IP address will be first transferred to a Google server in the USA and truncated there. The IP-anonymisation is active on this website</p>
                    <p>Google will use this information on behalf of the operator of this website for the purpose of evaluating your use of the website, compiling reports on website activity for website operators and providing them other services relating to website activity and internet usage.</p>
                    <p>The IP-address, that your Browser conveys within the scope of Google Analytics, will not be associated with any other data held by Google. You may refuse the use of cookies by selecting the appropriate settings on your browser, however please note that if you do this you may not be able to use the full functionality of this website. You can also opt-out from being tracked by Google Analytics with effect for the future by downloading and installing Google Analytics Opt-out Browser Addon for your current web browser: <a href="https://tools.google.com/dlpage/gaoptout?hl=en" target="_blank" rel="noopener noreferrer">https://tools.google.com/dlpage/gaoptout?hl=en</a>.</p>
                </section>

                <section>
                    <h2>Links to other websites</h2>
                    <p>Our website may contain links to other websites of interest. However, once you have used these links to leave our site, you should note that we do not have any control over that other website. Therefore, we cannot be responsible for the protection and privacy of any information which you provide whilst visiting such sites and such sites are not governed by this privacy statement. You should exercise caution and look at the privacy statement applicable to the website in question.</p>
                </section>

                <section>
                    <h2>Controlling your personal information</h2>
                    <p>You may choose to restrict the collection or use of your personal information in the following ways:</p>
                    <ul>
                        <li>Whenever you are asked to fill in a form on the website, look for the box that you can click to indicate that you do not want the information to be used by anybody for direct marketing purposes</li>
                        <li>If you have previously agreed to us using your personal information for direct marketing purposes, you may change your mind at any time by sending us an email here <a href="mailto:info@diamantidesyachting.com">info@diamantidesyachting.com</a></li>
                    </ul>
                    <p>We will not sell, distribute or lease your personal information to third parties unless we have your permission or are required by law to do so. We may use your personal information to send you promotional information about third parties which we think you may find interesting if you tell us that you wish this to happen.</p>
                    <p>You may request details of personal information which we hold about you under the Person Protection Law 138(Ι)/2001. A small fee will be payable. If you would like a copy of the information held on you please send us an email here <a href="mailto:info@diamantidesyachting.com">info@diamantidesyachting.com</a></p>
                    <p>If you believe that any information we are holding on you is incorrect or incomplete, please send us an email here <a href="mailto:info@diamantidesyachting.com">info@diamantidesyachting.com</a>. We will promptly correct any information found to be incorrect.</p>
                </section>
            </div>
        </div>
    );
};

export default PrivacyPolicyPage;
