import { useEffect } from 'react';
import { useLanguage } from '../context/LanguageContext';
import './PrivacyPolicy.css';

const content = {
    en: (
        <>
            <section>
                <p>This privacy policy sets out how Diamantides Yachting uses and protects any information that you give to <a href="https://www.diamantidesyachting.com">www.diamantidesyachting.com</a> when you use this website.</p>
                <p>Diamantides Yachting is committed to ensuring that your privacy is protected. Should we ask you to provide certain information by which you can be identified when using this website, then you can be assured that it will only be used in accordance with this privacy statement.</p>
                <p>Diamantides Yachting may change this policy from time to time by updating this page. You should check this page from time to time to ensure that you are happy with any changes. This policy is effective from 01/12/2021.</p>
            </section>

            <section>
                <h2>What we collect</h2>
                <p>We may collect the following information:</p>
                <ul>
                    <li>name</li>
                    <li>surname</li>
                    <li>contact number</li>
                    <li>email</li>
                </ul>
            </section>

            <section>
                <h2>What we do with the information we gather</h2>
                <p>We require this information to understand your needs and provide you with a better service, and in particular for the following reasons:</p>
                <ul>
                    <li>Internal record keeping.</li>
                    <li>We may use the information to improve our products and services.</li>
                    <li>We may periodically send promotional emails about new products, special offers or other information which we think you may find interesting using the email address which you have provided.</li>
                    <li>From time to time, we may also use your information to contact you for market research purposes. We may contact you by email, phone, fax or mail. We may use the information to customize the website according to your interests.</li>
                </ul>
            </section>

            <section>
                <h2>Security</h2>
                <p>We are committed to ensuring that your information is secure. In order to prevent unauthorized access or disclosure, we have put in place suitable physical, electronic and managerial procedures to safeguard and secure the information we collect online.</p>
            </section>

            <section>
                <h2>How we use cookies</h2>
                <p>A cookie is a small file that asks permission to be placed on your computer’s hard drive. Once you agree, the file is added and the cookie helps analyse web traffic or lets you know when you visit a particular site. Cookies allow web applications to respond to you as an individual. The web application can tailor its operations to your needs, likes and dislikes by gathering and remembering information about your preferences.</p>
                <p>We use traffic log cookies to identify which pages are being used. This helps us analyse data about web page traffic and improve our website in order to tailor it to customer needs. We only use this information for statistical analysis purposes and then the data is removed from the system.</p>
                <p>Overall, cookies help us provide you with a better website, by enabling us to monitor which pages you find useful and which you do not. A cookie in no way gives us access to your computer or any information about you, other than the data you choose to share with us.</p>
                <p>You can choose to accept or decline cookies. Most web browsers automatically accept cookies, but you can usually modify your browser setting to decline cookies if you prefer. This may prevent you from taking full advantage of the website.</p>
            </section>

            <section>
                <h2>Google Analytics</h2>
                <p>This website uses Google Analytics, a web analytics service provided by Google, Inc. (“Google”). Google Analytics uses “cookies”, which are text files placed on your computer, to help the website analyze how users use the site. The information generated by the cookie about your use of the website will be transmitted to and stored by Google on servers in the United States.</p>
                <p>In case IP-anonymisation is activated on this website, your IP address will be truncated within the area of Member States of the European Union or other parties to the Agreement on the European Economic Area. Only in exceptional cases the whole IP address will be first transferred to a Google server in the USA and truncated there. The IP-anonymisation is active on this website</p>
                <p>Google will use this information on behalf of the operator of this website for the purpose of evaluating your use of the website, compiling reports on website activity for website operators and providing them other services relating to website activity and internet usage.</p>
                <p>The IP-address, that your Browser conveys within the scope of Google Analytics, will not be associated with any other data held by Google. You may refuse the use of cookies by selecting the appropriate settings on your browser, however please note that if you do this you may not be able to use the full functionality of this website. You can also opt-out from being tracked by Google Analytics with effect for the future by downloading and installing Google Analytics Opt-out Browser Addon for your current web browser: <a href="https://tools.google.com/dlpage/gaoptout?hl=en" target="_blank" rel="noopener noreferrer">https://tools.google.com/dlpage/gaoptout?hl=en</a>.</p>
            </section>

            <section>
                <h2>Links to other websites</h2>
                <p>Our website may contain links to other websites of interest. However, once you have used these links to leave our site, you should note that we do not have any control over that other website. Therefore, we cannot be responsible for the protection and privacy of any information which you provide whilst visiting such sites and such sites are not governed by this privacy statement. You should exercise caution and look at the privacy statement applicable to the website in question.</p>
            </section>

            <section>
                <h2>Controlling your personal information</h2>
                <p>You may choose to restrict the collection or use of your personal information in the following ways:</p>
                <ul>
                    <li>Whenever you are asked to fill in a form on the website, look for the box that you can click to indicate that you do not want the information to be used by anybody for direct marketing purposes</li>
                    <li>If you have previously agreed to us using your personal information for direct marketing purposes, you may change your mind at any time by sending us an email here <a href="mailto:administration@diamantidesyachting.com">administration@diamantidesyachting.com</a></li>
                </ul>
                <p>We will not sell, distribute or lease your personal information to third parties unless we have your permission or are required by law to do so. We may use your personal information to send you promotional information about third parties which we think you may find interesting if you tell us that you wish this to happen.</p>
                <p>You may request details of personal information which we hold about you under the Person Protection Law 138(Ι)/2001. A small fee will be payable. If you would like a copy of the information held on you please send us an email here <a href="mailto:administration@diamantidesyachting.com">administration@diamantidesyachting.com</a></p>
                <p>If you believe that any information we are holding on you is incorrect or incomplete, please send us an email here <a href="mailto:administration@diamantidesyachting.com">administration@diamantidesyachting.com</a>. We will promptly correct any information found to be incorrect.</p>
            </section>
        </>
    ),
    ru: (
        <>
            <section>
                <p>Настоящая политика конфиденциальности описывает, как Diamantides Yachting использует и защищает любую информацию, которую вы предоставляете сайту <a href="https://www.diamantidesyachting.com">www.diamantidesyachting.com</a> при его использовании.</p>
                <p>Diamantides Yachting стремится обеспечить защиту вашей конфиденциальности. Если при использовании данного сайта мы просим вас предоставить определённую информацию, по которой вас можно идентифицировать, вы можете быть уверены, что она будет использована исключительно в соответствии с настоящим заявлением о конфиденциальности.</p>
                <p>Diamantides Yachting может время от времени изменять данную политику, обновляя эту страницу. Рекомендуем периодически проверять эту страницу, чтобы убедиться, что вас устраивают возможные изменения. Данная политика действует с 01/12/2021.</p>
            </section>

            <section>
                <h2>Какие данные мы собираем</h2>
                <p>Мы можем собирать следующую информацию:</p>
                <ul>
                    <li>имя</li>
                    <li>фамилия</li>
                    <li>контактный номер</li>
                    <li>электронная почта</li>
                </ul>
            </section>

            <section>
                <h2>Как мы используем собранную информацию</h2>
                <p>Эта информация нужна нам, чтобы понимать ваши потребности и предоставлять более качественный сервис, в частности для следующих целей:</p>
                <ul>
                    <li>Внутренний учёт.</li>
                    <li>Мы можем использовать информацию для улучшения наших продуктов и услуг.</li>
                    <li>Мы можем периодически отправлять рекламные письма о новых продуктах, специальных предложениях или другой информации, которая может вас заинтересовать, на указанный вами адрес электронной почты.</li>
                    <li>Время от времени мы также можем использовать вашу информацию, чтобы связаться с вами в целях маркетинговых исследований. Мы можем связаться с вами по электронной почте, телефону, факсу или почте. Мы можем использовать информацию для адаптации сайта под ваши интересы.</li>
                </ul>
            </section>

            <section>
                <h2>Безопасность</h2>
                <p>Мы стремимся обеспечить безопасность вашей информации. Для предотвращения несанкционированного доступа или разглашения мы внедрили соответствующие физические, электронные и организационные процедуры для защиты и сохранности информации, которую мы собираем онлайн.</p>
            </section>

            <section>
                <h2>Как мы используем файлы cookie</h2>
                <p>Cookie — это небольшой файл, который запрашивает разрешение на размещение на жёстком диске вашего компьютера. После вашего согласия файл добавляется, и cookie помогает анализировать веб-трафик или сообщает о посещении определённого сайта. Файлы cookie позволяют веб-приложениям реагировать на вас как на отдельного пользователя. Веб-приложение может адаптировать свою работу под ваши потребности и предпочтения, собирая и запоминая информацию о них.</p>
                <p>Мы используем cookie журналов трафика, чтобы определить, какие страницы используются. Это помогает нам анализировать данные о посещаемости страниц и улучшать сайт, адаптируя его под потребности клиентов. Мы используем эту информацию только для целей статистического анализа, после чего данные удаляются из системы.</p>
                <p>В целом файлы cookie помогают нам сделать сайт лучше, позволяя отслеживать, какие страницы вы находите полезными, а какие нет. Cookie ни в коем случае не даёт нам доступ к вашему компьютеру или какой-либо информации о вас, кроме данных, которыми вы решили с нами поделиться.</p>
                <p>Вы можете принять или отклонить файлы cookie. Большинство браузеров автоматически принимают cookie, но вы обычно можете изменить настройки браузера, чтобы отклонять их. Это может помешать вам использовать все возможности сайта.</p>
            </section>

            <section>
                <h2>Google Analytics</h2>
                <p>Этот сайт использует Google Analytics — сервис веб-аналитики, предоставляемый компанией Google, Inc. («Google»). Google Analytics использует «cookie» — текстовые файлы, размещаемые на вашем компьютере, чтобы помочь сайту анализировать, как пользователи его используют. Информация, генерируемая cookie о вашем использовании сайта, передаётся и хранится Google на серверах в США.</p>
                <p>Если на сайте активирована анонимизация IP, ваш IP-адрес будет усечён в пределах государств — членов Европейского союза или других сторон Соглашения о Европейской экономической зоне. Только в исключительных случаях полный IP-адрес будет сначала передан на сервер Google в США и усечён там. Анонимизация IP активна на этом сайте.</p>
                <p>Google будет использовать эту информацию от имени оператора сайта для оценки вашего использования сайта, составления отчётов об активности сайта для операторов и предоставления им других услуг, связанных с активностью сайта и использованием интернета.</p>
                <p>IP-адрес, передаваемый вашим браузером в рамках Google Analytics, не будет связан с какими-либо другими данными, хранящимися у Google. Вы можете отказаться от использования cookie, выбрав соответствующие настройки в браузере, однако учтите, что в этом случае вы, возможно, не сможете использовать весь функционал сайта. Вы также можете отказаться от отслеживания Google Analytics на будущее, скачав и установив дополнение для браузера Google Analytics Opt-out: <a href="https://tools.google.com/dlpage/gaoptout?hl=ru" target="_blank" rel="noopener noreferrer">https://tools.google.com/dlpage/gaoptout?hl=ru</a>.</p>
            </section>

            <section>
                <h2>Ссылки на другие сайты</h2>
                <p>Наш сайт может содержать ссылки на другие интересные сайты. Однако, перейдя по этим ссылкам и покинув наш сайт, обратите внимание, что мы не контролируем эти сайты. Поэтому мы не можем нести ответственность за защиту и конфиденциальность любой информации, которую вы предоставляете при посещении таких сайтов, и они не регулируются настоящим заявлением о конфиденциальности. Будьте осторожны и ознакомьтесь с заявлением о конфиденциальности соответствующего сайта.</p>
            </section>

            <section>
                <h2>Управление вашей персональной информацией</h2>
                <p>Вы можете ограничить сбор или использование вашей персональной информации следующими способами:</p>
                <ul>
                    <li>Когда вас просят заполнить форму на сайте, ищите поле, которое можно отметить, чтобы указать, что вы не хотите, чтобы информация использовалась кем-либо в целях прямого маркетинга</li>
                    <li>Если вы ранее согласились на использование вашей персональной информации в целях прямого маркетинга, вы можете в любой момент изменить своё решение, написав нам на <a href="mailto:administration@diamantidesyachting.com">administration@diamantidesyachting.com</a></li>
                </ul>
                <p>Мы не будем продавать, распространять или передавать вашу персональную информацию третьим лицам без вашего разрешения, за исключением случаев, предусмотренных законом. Мы можем использовать вашу персональную информацию для отправки рекламных материалов третьих лиц, которые могут вас заинтересовать, если вы сообщите нам о таком желании.</p>
                <p>Вы можете запросить сведения о персональной информации, которую мы храним о вас, в соответствии с Законом о защите личности 138(Ι)/2001. Взимается небольшая плата. Если вы хотите получить копию хранящейся о вас информации, напишите нам на <a href="mailto:administration@diamantidesyachting.com">administration@diamantidesyachting.com</a></p>
                <p>Если вы считаете, что какая-либо информация, которую мы храним о вас, неверна или неполна, напишите нам на <a href="mailto:administration@diamantidesyachting.com">administration@diamantidesyachting.com</a>. Мы оперативно исправим любую информацию, признанную неверной.</p>
            </section>
        </>
    )
};

const titles = {
    en: 'Privacy Policy',
    ru: 'Политика конфиденциальности'
};

const PrivacyPolicyPage = () => {
    const { currentLang } = useLanguage();

    useEffect(() => {
        window.scrollTo(0, 0);
    }, []);

    return (
        <div className="privacy-policy-page">
            <div className="privacy-policy-hero">
                <div className="container">
                    <h1>{titles[currentLang] || titles.en}</h1>
                </div>
            </div>

            <div className="privacy-policy-content container">
                {content[currentLang] || content.en}
            </div>
        </div>
    );
};

export default PrivacyPolicyPage;
